// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5_AFEqrPjLJ43WsNYHJkLRZkwC19k95Q',
    appId: '1:257696085265:web:a88afa47c9ac6fc8b908b0',
    messagingSenderId: '257696085265',
    projectId: 'stoon-74b9e',
    authDomain: 'stoon-74b9e.firebaseapp.com',
    storageBucket: 'stoon-74b9e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9ed57rubUkVwnn4YLErhSn3rTHV36ILw',
    appId: '1:257696085265:android:5175ef0b8eebba40b908b0',
    messagingSenderId: '257696085265',
    projectId: 'stoon-74b9e',
    storageBucket: 'stoon-74b9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRw1_gmK6_-VwcP69cKxkY2M8jqYlwaAE',
    appId: '1:257696085265:ios:8fd082cf2d5626cab908b0',
    messagingSenderId: '257696085265',
    projectId: 'stoon-74b9e',
    storageBucket: 'stoon-74b9e.appspot.com',
    iosClientId:
        '257696085265-lel62ml9rqqq567f560vd84fc5qv8i8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.stoon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRw1_gmK6_-VwcP69cKxkY2M8jqYlwaAE',
    appId: '1:257696085265:ios:8fd082cf2d5626cab908b0',
    messagingSenderId: '257696085265',
    projectId: 'stoon-74b9e',
    storageBucket: 'stoon-74b9e.appspot.com',
    iosClientId:
        '257696085265-lel62ml9rqqq567f560vd84fc5qv8i8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.stoon',
  );
}
